// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPlAfISvXpfVmUvWxn8GoO4J9SVdu7XyA',
    appId: '1:528601843186:web:5cbb38783182f317dcd76b',
    messagingSenderId: '528601843186',
    projectId: 'capstone-cfbea',
    authDomain: 'capstone-cfbea.firebaseapp.com',
    storageBucket: 'capstone-cfbea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmAF8yy-DIj0zK6aUzQ3Mcnnoy_lCYLkE',
    appId: '1:336636327627:android:c448c37b78be52c53b0d4e',
    messagingSenderId: '336636327627',
    projectId: 'capstone-c1ee2',
    storageBucket: 'capstone-c1ee2.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPlAfISvXpfVmUvWxn8GoO4J9SVdu7XyA',
    appId: '1:528601843186:web:1e409c4e8792d057dcd76b',
    messagingSenderId: '528601843186',
    projectId: 'capstone-cfbea',
    authDomain: 'capstone-cfbea.firebaseapp.com',
    storageBucket: 'capstone-cfbea.appspot.com',
  );
}